let products = [
    {
      title: "PYTHON",
      name: "Python programming for beginers",
      by: "By:Kethrin",
      date: "19th September 2020",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS",
      time: 40,
      price: 1500,
    },
    {
      title: "MS EXCEL",
      name: "MS excel beginer to advance",
      by: "By:shekher",
      date: "19th August 2021",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://www.javatpoint.com/excel-tutorial",
      time: 4000,
      price: 400,
    },
    {
      title: "SQL",
      name: "Be an expert in sql",
      by: "By:Saroj yadav",
      date: "03th july 2021",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://www.simplilearn.com/tutorials/sql-tutorial/sql-advanced",
      time: 100,
      price: 6000,
    },
    {
      title: "DJANGO",
      name: "Django framework for intermidiate",
      by: "By:Paul Johnson",
      date: "19th March 2017",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://docs.djangoproject.com/en/3.2/",
      time: 300,
      price: 3999,
    },
    {
      title: "MEDIA QUERIES",
      name: "Create responsive pages using css media queries",
      by: "By:Ashish Mehra",
      date: "04th june 2019",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://docs.djangoproject.com/en/3.2/",
      time: 123,
      price: 399,
    },
    {
      title: "ASYNC",
      name: "Learn promies be expert in async and awaits ",
      by: "By:Shivani Chaudhari",
      date: "01th January 2018",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await",
      time: 320,
      price: 490,
    },
    {
      title: "LEARN FIGMA",
      name: "Create and design your own figma based website ",
      by: "By:Tejasvi Singh",
      date: "09th april 2013",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://mockitt.wondershare.com/figma/figma-tutorial.html",
      time: 600,
      price: 999,
    },
    {
      title: "REACT",
      name: "Create and design your own first website ",
      by: "By:shekhar",
      date: "09th may 2018",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://www.tutorialspoint.com/react_native/react_native_overview.htm",
      time: 4500,
      price: 5999,
    },
    {
      title: "DSA",
      name: "Be a pro in data structures and algorithms",
      by: "By:Abdul Bari",
      date: "09th october 2020",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://www.geeksforgeeks.org/data-structures/",
      time: 8000,
      price: 10000,
    },
    {
      title: "DOCKERS",
      name: "Docker for develpers ",
      by: "By:Peter Dakota ",
      date: "28th February 2020",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
      time: 3000,
      price: 9550,
    },
    {
      title: "APTITUDE & REASONING ",
      name: "Learn aptitude and reasoning to crack the GATE ",
      by: "By:Swastika Mukharjee",
      date: "09th may 2018",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
      time: 780,
      price: 450,
    },
    {
      title: "HTML & CSS",
      name: "create atractive ui by using html and css ",
      by: "By:Viraat sharma",
      date: "21th Februay 2014",
      video: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
      time: 788,
      price: 900,
    },
  ];