let products1 = [
  {
      title: "Python",
      name: "Learn Python Programming Masterclass",
      by: "By:Kethrin",
      date: "19th September 2020",
      img: "https://miro.medium.com/max/840/1*RJMxLdTHqVBSijKmOO5MAg.jpeg",
      link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS",
      time: 40,
      price: 1500,
  },
  {
      title: "Spring",
      name: "Spring & Hibernate for Beginners (includes Spring Boot)",
      by: "By:shekher",
      date: "19th August 2021",
      img: "https://top10onlinecourses.com/wp-content/uploads/2019/01/Spring-Online-Courses-Training-with-Certification.png",
      link: "https://www.javatpoint.com/excel-tutorial",
      time: 4000,
      price: 400,
  },
  {
      title: "Deep Learning",
      name: "Deep Learning A-Z™: Hands-On Artificial Neural Networks",
      by: "By:Saroj yadav",
      date: "03th july 2021",
      img: "https://online.stanford.edu/sites/default/files/styles/figure_default/public/2018-06/computer-science-deep-learning_CS230.jpg?itok=N1p1SKlh",
      link: "https://www.simplilearn.com/tutorials/sql-tutorial/sql-advanced",
      time: 100,
      price: 6000,
  },
  {
      title: "Finance",
      name: "The Complete Financial Analyst Course 2021",
      by: "By:Paul Johnson",
      date: "19th March 2017",
      img: "https://www.proschoolonline.com/wp-content/uploads/2018/05/finance63-300x136.jpg",
      link: "https://docs.djangoproject.com/en/3.2/",
      time: 300,
      price: 3999,
  },
  {
      title: "  Scrum: The Basics",
      name: "If you've spent any time in the project management world, you've likely heard of scrum—the popular framework for managing complex processes.",
      by: "By:Ashish Mehra",
      date: "04th june 2019",
      img: "https://miro.medium.com/max/533/0*p5Or7ISfr_dlO6UX.png",
      link: "https://docs.djangoproject.com/en/3.2/",
      time: 123,
      price: 399,
  },
  {
      title: " Communicating with Confidence",
      name: "Most people are afraid of speaking in public, but effective oral communication is a key skill in business. ",
      by: "By:Shivani Chaudhari",
      date: "01th January 2018",
      img: "https://wompampsupport.azureedge.net/fetchimage?siteId=7783&url=https%3A%2F%2Fspie.org%2FImages%2FGraphics%2FPhotonics%2520Focus%2Fv1_iss4%2F6_Communicating%2520with%2520Confidence-920.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await",
      time: 320,
      price: 490,
  },
  {
      title: "Time Management",
      name: "Time Management Fundamentals",
      by: "By:Tejasvi Singh",
      date: "09th april 2013",
      img: "https://i.ytimg.com/vi/R6wOxVBlddM/maxresdefault.jpg",
      link: "https://mockitt.wondershare.com/figma/figma-tutorial.html",
      time: 600,
      price: 999,
  },
  {
      title: "REACT",
      name: "Create and design your own first website ",
      by: "By:shekhar",
      date: "09th may 2018",
      img: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://www.tutorialspoint.com/react_native/react_native_overview.htm",
      time: 4500,
      price: 5999,
  },
  {
      title: " Strategic Thinking",
      name: "Strategic thinking is the ability to think on a big and small scale",
      by: "By:Abdul Bari",
      date: "09th october 2020",
      img: "https://www.mckinsey.com/~/media/mckinsey/business%20functions/strategy%20and%20corporate%20finance/our%20insights/the%20strategy%20and%20corporate%20finance%20blog/how%20to%20unleash%20your%20strategic%20thinking/4rules-linkedin.png",
      link: "https://www.geeksforgeeks.org/data-structures/",
      time: 8000,
      price: 10000,
  },
  {
      title: "DOCKERS",
      name: "Docker for develpers ",
      by: "By:Peter Dakota ",
      date: "28th February 2020",
      img: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
      time: 3000,
      price: 9550,
  },
  {
      title: "APTITUDE & REASONING ",
      name: "Learn aptitude and reasoning to crack the GATE ",
      by: "By:Swastika Mukharjee",
      date: "09th may 2018",
      img: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Mozilla/QA/Running_automated_tests/Docker",
      time: 780,
      price: 450,
  },
  {
      title: "HTML & CSS",
      name: "create atractive ui by using html and css ",
      by: "By:Viraat sharma",
      date: "21th Februay 2014",
      img: "https://www.incimages.com/uploaded_files/image/1920x1080/public-speaking-1940x900_35061.jpg",
      link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
      time: 788,
      price: 900,
  },
];